### ISSUE TITLE
Adicionar uma forma de permitir que os comandos sejam executados apenas em um canal

### ISSUE THREAD

**Issue by thiagogebrim13** [TiaGoiNsaNy/BotEconomiaQuickDB#2]
Seria interessante uma forma de fazer que os comandos possam ser executados apenas em um canal especifico, outra ideia é adicionar um sistema que tenha como se casar usando o saldo

**Comment by TiaGoiNsaNy** [comment]
Você pode adicionar uma simples condição dentro do evento **Message**, onde ele só irá prosseguir caso o **ID** canal seja igual ao canal da sua escolha.

```js
if (<Message>.channel.id == "ID do canal") {
    // código
};
```

Não á motivo em mudar toda a estrutura do código para atender a um pedido específico.

**Comment by thiagogebrim13** [comment]
Bom, eu tentei colocar dessa forma, mas não consegui fazer funcionar.. https://prnt.sc/14eogb1

**Comment by TiaGoiNsaNy** [comment]
#### :thinking: Primeiramente você não entendeu sobre oque quis passar acima, foi mostrado a maneira simples para você verificar o **ID** do canal, já que você não adicionou nada dentro da condição, você pode usar o método abaixo:

```js
<Cliente>.on("message", message => {
    if (!message.channel.id == "ID do Canal") return;
    // Não retorna nada caso o ID não seja igual ao ID acima
});
```

## Espero ter ajudado! :heart:

**Comment by thiagogebrim13** [comment]
Tentei e mesmo assim não deu, pensei ser algo que fiz errado nas minhas alterações do código e voltei ele a estaca zero, e mesmo assim não consigo fazer funcionar.. 
![image](https://user-images.githubusercontent.com/75040244/121027080-101b5c00-c77d-11eb-8f47-c1b2eef6d616.png)

**Comment by TiaGoiNsaNy** [comment]
:thinking: Não sei oque pode está acontecendo, pois o código não possui nada de errado, caso você queira conversar comigo, vá pelo meu Discord abaixo:

**Discord:** `TiaGoiNsaNy#9903`

:heart: Caso eu não seja um preguiçoso, eu irei responder rapido!
